// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecwggoowsfdjrrfeypfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjd2dnb293c2ZkanJyZmV5cGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDM5OTgsImV4cCI6MjA1ODgxOTk5OH0.9mmEcgpLRMuoNiQ_JBrP0Pgr4ayHqiyPIKgGmhmz438";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);